config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :projetos
  end
  namespace :admin do
    resources :clientes
    resources :administradores
    resources :departamentos
  end

end

app/models/admin/cliente.rb
class Admin::Cliente < ApplicationRecord
  has_many :projetos, class_name: 'Admin::Projeto'
  validates :cnpj, uniqueness: true

end

app/controllers/admin/clientes_controller.rb
class Admin::ClientesController < ApplicationController
  before_action :set_admin_cliente, only: [:show, :edit, :update, :destroy]
  # GET /admin/clientes
  # GET /admin/clientes.json
  def index
    @admin_clientes = Admin::Cliente.all
  end

  # GET /admin/clientes/1
  # GET /admin/clientes/1.json
  def show
  end

  # GET /admin/clientes/new
  def new
    @admin_cliente = Admin::Cliente.new
  end

  # GET /admin/clientes/1/edit
  def edit
  end

  # POST /admin/clientes
  # POST /admin/clientes.json
  def create
    @admin_cliente = Admin::Cliente.new(admin_cliente_params)

    respond_to do |format|
      if @admin_cliente.save
        format.html { redirect_to admin_clientes_url, notice: 'Cliente Cadastrado com Sucesso.' }
        format.json { render :show, status: :created, location: @admin_cliente }
      else
        format.html { render :new }
        format.json { render json: @admin_cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/clientes/1
  # PATCH/PUT /admin/clientes/1.json
  def update
    respond_to do |format|
      if @admin_cliente.update(admin_cliente_params)
        format.html { redirect_to @admin_cliente, notice: 'Cliente Atualizado com Sucesso.' }
        format.json { render :show, status: :ok, location: @admin_cliente }
      else
        format.html { render :edit }
        format.json { render json: @admin_cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/clientes/1
  # DELETE /admin/clientes/1.json
  def destroy
    @admin_cliente.destroy
    respond_to do |format|
      format.html { redirect_to admin_clientes_url, notice: 'Cliente Excluído com Sucesso..' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_cliente
      @admin_cliente = Admin::Cliente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_cliente_params
      params.require(:admin_cliente).permit(:razao_social, :cnpj, :nome_fantasia, :nome_responsavel, :email, :telefone, :status)
    end
end

app/helpers/admin/clientes_helper.rb
module Admin::ClientesHelper
end

app/views/admin/clientes/_form.html.erb
<%= form_for(@admin_cliente, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @admin_cliente.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Fechar</span></button>
      <h4>Verifique os campos abaixo:</h4>

      <ul>
      <% @admin_cliente.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :razao_social, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :razao_social, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :cnpj, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :cnpj, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :nome_fantasia, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :nome_fantasia, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :nome_responsavel, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :nome_responsavel, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :email, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :email, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :telefone, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :telefone, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :status, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.check_box :status, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/admin/clientes/edit.html.erb
<div class="page-header">
  <%= link_to admin_clientes_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Voltar
  <% end %>
  <%= link_to @admin_cliente, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Mostrar
  <% end %>
  <h1>Editar cliente</h1>
</div>

<%= render 'form' %>

app/views/admin/clientes/index.html.erb
<div class="page-header">
  <%= link_to new_admin_cliente_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    Novo Cliente
  <% end %>
  <h1>Lista de Clientes</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Razão Social</th>
            <th>Cnpj</th>
            <th>Nome Fantasia</th>
            <th>Nome Responsável</th>
            <th>Email</th>
            <th>Telefone</th>
            <th>Status</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @admin_clientes) do |admin_cliente| %>
            <td><%= admin_cliente.razao_social %></td>
            <td><%= admin_cliente.cnpj %></td>
            <td><%= admin_cliente.nome_fantasia %></td>
            <td><%= admin_cliente.nome_responsavel %></td>
            <td><%= admin_cliente.email %></td>
            <td><%= admin_cliente.telefone %></td>
            <td><%= admin_cliente.status %></td>
            <td><%= link_to 'Projetos Cliente', admin_cliente %></td>
        <td><%= link_to 'Editar', edit_admin_cliente_path(admin_cliente) %></td>
        <td><%= link_to 'Apagar', admin_cliente, method: :delete, data: { confirm: 'Você tem Certeza que deseja Excluir?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/clientes/new.html.erb
<div class="page-header">
  <%= link_to admin_clientes_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Voltar
  <% end %>
  <h1>Novo Cliente</h1>
</div>

<%= render 'form' %>

app/views/admin/clientes/show.html.erb
<div class="page-header">
  <%= link_to admin_clientes_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Voltar
  <% end %>
  <%= link_to edit_admin_cliente_path(@admin_cliente), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Editar
  <% end %>
  <h1>Detalhes Cliente</h1>
</div>

<dl class="dl-horizontal">
  <dt>Razão Social:</dt>
  <dd><%= @admin_cliente.razao_social %></dd>

  <dt>Cnpj:</dt>
  <dd><%= @admin_cliente.cnpj %></dd>

  <dt>Nome Fantasia:</dt>
  <dd><%= @admin_cliente.nome_fantasia %></dd>

  <dt>Nome Responsável:</dt>
  <dd><%= @admin_cliente.nome_responsavel %></dd>

  <dt>Email:</dt>
  <dd><%= @admin_cliente.email %></dd>

  <dt>Telefone:</dt>
  <dd><%= @admin_cliente.telefone %></dd>

  <dt>Status:</dt>
  <dd><%= @admin_cliente.status %></dd>

</dl>
<div class="page-header">
  <%= link_to new_admin_projeto_path(id:@admin_cliente), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    Novo Projeto
  <% end %>
  <h1>Projetos</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Nome projeto</th>
            <th>Responsavel projeto</th>
            <th>Email responsavel</th>
            <th>Pdv</th>
            <th>Pdv qtd</th>
            <th>Admin cliente</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @admin_cliente.projetos) do |projeto| %>
            <td><%= projeto.nome_projeto %></td>
            <td><%= projeto.responsavel_projeto %></td>
            <td><%= projeto.email_responsavel %></td>
            <td><%= projeto.pdv %></td>
            <td><%= projeto.pdv_qtd %></td>
            <td><%= projeto.cliente %></td>
            <td><%= link_to 'Mostrar', projeto %></td>
        <td><%= link_to 'Editar', edit_admin_projeto_path(projeto) %></td>
        <td><%= link_to 'Apagar', projeto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>