config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :projetos
  end
  namespace :admin do
    resources :clientes
    resources :administradores
    resources :departamentos
  end

end

app/controllers/admin/administradores_controller.rb
class Admin::AdministradoresController < ApplicationController
  before_action :set_admin_administrador, only: [:show, :edit, :update, :destroy]

  # GET /admin/administradores
  # GET /admin/administradores.json
  def index
    @admin_administradores = Admin::Administrador.all
  end

  # GET /admin/administradores/1
  # GET /admin/administradores/1.json
  def show
  end

  # GET /admin/administradores/new
  def new
    @admin_administrador = Admin::Administrador.new
  end

  # GET /admin/administradores/1/edit
  def edit
  end

  # POST /admin/administradores
  # POST /admin/administradores.json
  def create
    @admin_administrador = Admin::Administrador.new(admin_administrador_params)

    respond_to do |format|
      if @admin_administrador.save
        format.html { redirect_to @admin_administrador, notice: 'Administrador was successfully created.' }
        format.json { render :show, status: :created, location: @admin_administrador }
      else
        format.html { render :new }
        format.json { render json: @admin_administrador.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/administradores/1
  # PATCH/PUT /admin/administradores/1.json
  def update
    respond_to do |format|
      if @admin_administrador.update(admin_administrador_params)
        format.html { redirect_to @admin_administrador, notice: 'Administrador was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_administrador }
      else
        format.html { render :edit }
        format.json { render json: @admin_administrador.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/administradores/1
  # DELETE /admin/administradores/1.json
  def destroy
    @admin_administrador.destroy
    respond_to do |format|
      format.html { redirect_to admin_administradores_url, notice: 'Administrador was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_administrador
      @admin_administrador = Admin::Administrador.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_administrador_params
      params.require(:admin_administrador).permit(:nome, :cpf, :admin_departamento_id, :email, :senha)
    end
end

app/helpers/admin/administradores_helper.rb
module Admin::AdministradoresHelper
end

app/views/admin/administradores/_form.html.erb
<%= form_for(@admin_administrador, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @admin_administrador.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4>Verifique os campos abaixo:</h4>

      <ul>
      <% @admin_administrador.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :nome, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :nome, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :cpf, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :cpf, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :admin_departamento, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :admin_departamento, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :email, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :email, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :senha, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :senha, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/admin/administradores/edit.html.erb
<div class="page-header">
  <%= link_to admin_administradores_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Voltar
  <% end %>
  <%= link_to @admin_administrador, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Mostrar
  <% end %>
  <h1>Editar admin_administrador</h1>
</div>

<%= render 'form' %>

app/views/admin/administradores/index.html.erb
<div class="page-header">
  <%= link_to new_admin_administrador_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    Novo Administrador
  <% end %>
  <h1>Lista de admin_administradores</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Nome</th>
            <th>Cpf</th>
            <th>Admin departamento</th>
            <th>Email</th>
            <th>Senha</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @admin_administradores) do |admin_administrador| %>
            <td><%= admin_administrador.nome %></td>
            <td><%= admin_administrador.cpf %></td>
            <td><%= admin_administrador.admin_departamento %></td>
            <td><%= admin_administrador.email %></td>
            <td><%= admin_administrador.senha %></td>
            <td><%= link_to 'Mostrar', admin_administrador %></td>
        <td><%= link_to 'Editar', edit_admin_administrador_path(admin_administrador) %></td>
        <td><%= link_to 'Apagar', admin_administrador, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/administradores/new.html.erb
<div class="page-header">
  <%= link_to admin_administradores_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Voltar
  <% end %>
  <h1>Novo admin_administrador</h1>
</div>

<%= render 'form' %>

app/views/admin/administradores/show.html.erb
<div class="page-header">
  <%= link_to admin_administradores_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Voltar
  <% end %>
  <%= link_to edit_admin_administrador_path(@admin_administrador), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Editar
  <% end %>
  <h1>Mostrar admin_administrador</h1>
</div>

<dl class="dl-horizontal">
  <dt>Nome:</dt>
  <dd><%= @admin_administrador.nome %></dd>

  <dt>Cpf:</dt>
  <dd><%= @admin_administrador.cpf %></dd>

  <dt>Admin departamento:</dt>
  <dd><%= @admin_administrador.admin_departamento %></dd>

  <dt>Email:</dt>
  <dd><%= @admin_administrador.email %></dd>

  <dt>Senha:</dt>
  <dd><%= @admin_administrador.senha %></dd>

</dl>