config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :projetos
  end
  namespace :admin do
    resources :clientes
    resources :administradores
    resources :departamentos
  end

end

app/models/admin/departamento.rb
class Admin::Departamento < ApplicationRecord
end

app/controllers/admin/departamentos_controller.rb
class Admin::DepartamentosController < ApplicationController
  before_action :set_admin_departamento, only: [:show, :edit, :update, :destroy]

  # GET /admin/departamentos
  # GET /admin/departamentos.json
  def index
    @admin_departamentos = Admin::Departamento.all
  end

  # GET /admin/departamentos/1
  # GET /admin/departamentos/1.json
  def show
  end

  # GET /admin/departamentos/new
  def new
    @admin_departamento = Admin::Departamento.new
  end

  # GET /admin/departamentos/1/edit
  def edit
  end

  # POST /admin/departamentos
  # POST /admin/departamentos.json
  def create
    @admin_departamento = Admin::Departamento.new(admin_departamento_params)

    respond_to do |format|
      if @admin_departamento.save
        format.html { redirect_to @admin_departamento, notice: 'Departamento was successfully created.' }
        format.json { render :show, status: :created, location: @admin_departamento }
      else
        format.html { render :new }
        format.json { render json: @admin_departamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/departamentos/1
  # PATCH/PUT /admin/departamentos/1.json
  def update
    respond_to do |format|
      if @admin_departamento.update(admin_departamento_params)
        format.html { redirect_to @admin_departamento, notice: 'Departamento was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_departamento }
      else
        format.html { render :edit }
        format.json { render json: @admin_departamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/departamentos/1
  # DELETE /admin/departamentos/1.json
  def destroy
    @admin_departamento.destroy
    respond_to do |format|
      format.html { redirect_to admin_departamentos_url, notice: 'Departamento was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_departamento
      @admin_departamento = Admin::Departamento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_departamento_params
      params.require(:admin_departamento).permit(:nome)
    end
end

app/helpers/admin/departamentos_helper.rb
module Admin::DepartamentosHelper
end

app/views/admin/departamentos/_form.html.erb
<%= form_for(@admin_departamento, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @admin_departamento.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4>Verifique os campos abaixo:</h4>

      <ul>
      <% @admin_departamento.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :nome, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :nome, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/admin/departamentos/edit.html.erb
<div class="page-header">
  <%= link_to admin_departamentos_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Voltar
  <% end %>
  <%= link_to @admin_departamento, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Mostrar
  <% end %>
  <h1>Editar admin_departamento</h1>
</div>

<%= render 'form' %>

app/views/admin/departamentos/new.html.erb
<div class="page-header">
  <%= link_to admin_departamentos_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Voltar
  <% end %>
  <h1>Novo admin_departamento</h1>
</div>

<%= render 'form' %>

app/views/admin/departamentos/show.html.erb
<div class="page-header">
  <%= link_to admin_departamentos_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Voltar
  <% end %>
  <%= link_to edit_admin_departamento_path(@admin_departamento), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Editar
  <% end %>
  <h1>Mostrar admin_departamento</h1>
</div>

<dl class="dl-horizontal">
  <dt>Nome:</dt>
  <dd><%= @admin_departamento.nome %></dd>

</dl>